package kerho.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.27 22:26:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta111 
   * @throws PoikkeusException when error
   */
  @Test
  public void testLueTiedostosta111() throws PoikkeusException {    // Jasenet: 111
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen1 = new Jasen(), jasen2 = new Jasen(); 
    jasen1.taytaJasen(); 
    jasen2.taytaJasen(); 
    jasenet.lueTiedostosta(); 
    int lkm1 = jasenet.getLkm(); 
    jasenet.lisaa(jasen1); 
    jasenet.lisaa(jasen2); 
    jasenet.tallenna(); 
    assertEquals("From: Jasenet line: 124", lkm1 + 2, jasenet.getLkm()); 
    jasenet.poista(jasen1.getTunnusNro()); 
    jasenet.poista(jasen2.getTunnusNro()); 
    assertEquals("From: Jasenet line: 127", lkm1, jasenet.getLkm()); 
    jasenet.tallenna(); 
    jasenet = new Jasenet(); 
    assertEquals("From: Jasenet line: 130", 0, jasenet.getLkm()); 
    jasenet.lisaa(jasen1); 
    jasenet.lisaa(jasen2); 
    Iterator<Jasen> i = jasenet.iterator(); 
    assertEquals("From: Jasenet line: 134", jasen1, i.next()); 
    assertEquals("From: Jasenet line: 135", jasen2, i.next()); 
    assertEquals("From: Jasenet line: 136", false, i.hasNext()); 
    assertEquals("From: Jasenet line: 137", 2, jasenet.getLkm()); 
    jasenet.poista(jasen1.getTunnusNro()); 
    jasenet.poista(jasen2.getTunnusNro()); 
    assertEquals("From: Jasenet line: 140", 0, jasenet.getLkm()); 
    jasenet = new Jasenet(); 
    jasenet.lueTiedostosta(); 
    jasenet.tallenna(); 
    assertEquals("From: Jasenet line: 144", lkm1, jasenet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa233 
   * @throws PoikkeusException when error
   */
  @Test
  public void testLisaa233() throws PoikkeusException {    // Jasenet: 233
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen1 = new Jasen(); 
    Jasen jasen2 = new Jasen(); 
    assertEquals("From: Jasenet line: 238", 0, jasenet.getLkm()); 
    jasenet.lisaa(jasen1); assertEquals("From: Jasenet line: 239", 1, jasenet.getLkm()); 
    jasenet.lisaa(jasen2); assertEquals("From: Jasenet line: 240", 2, jasenet.getLkm()); 
    jasenet.lisaa(jasen1); assertEquals("From: Jasenet line: 241", 3, jasenet.getLkm()); 
    jasenet.lisaa(jasen2); assertEquals("From: Jasenet line: 242", 4, jasenet.getLkm()); 
    jasenet.lisaa(jasen1); assertEquals("From: Jasenet line: 243", 5, jasenet.getLkm()); 
    jasenet.lisaa(jasen2); assertEquals("From: Jasenet line: 244", 6, jasenet.getLkm()); 
  } // Generated by ComTest END
}