package kerho.test;
// Generated by ComTest BEGIN
import kerho.Jasen;
import kerho.Kerho;
import kerho.Kirja;
import static org.junit.Assert.*;
import org.junit.*;
import static kerho.Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.27 21:46:37 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KerhoTest {



  // Generated by ComTest BEGIN
  /** testMain321 */
  @Test
  public void testMain321() {    // Kerho: 321
    Kerho kerho = new Kerho(); 
    Jasen jasen1 = new Jasen(); 
    Jasen jasen2 = new Jasen(); 
    jasen1.rekisteroi(); 
    jasen2.rekisteroi(); 
    jasen1.taytaJasen(); 
    jasen2.taytaJasen(); 
    kerho.lisaa(jasen1); 
    kerho.lisaa(jasen2); 
    assertEquals("From: Kerho line: 334", 2, kerho.getJasenia()); 
    Kirja kirja1 = new Kirja(); 
    Kirja kirja2 = new Kirja(); 
    kirja1.rekisteroi(); 
    kirja2.rekisteroi(); 
    kirja1.taytaKirja(); 
    kirja2.taytaKirja(); 
    kerho.lisaa(kirja1); 
    kerho.lisaa(kirja2); 
    assertEquals("From: Kerho line: 343", 2, kerho.getKirjoja()); 
    kerho.poista(jasen1); 
    assertEquals("From: Kerho line: 345", 1, kerho.getJasenia()); 
    kerho.poista(kirja1); 
    assertEquals("From: Kerho line: 347", 1, kerho.getKirjoja()); 
  } // Generated by ComTest END
}