package kerho.test;
// Generated by ComTest BEGIN
import kerho.Kirjat;
import kerho.Kirja;
import static org.junit.Assert.*;
import org.junit.*;
import static kerho.Kirjat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 23:06:03 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** testMain271 */
  @Test
  public void testMain271() {    // Kirjat: 271
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(); 
    Kirja kirja2 = new Kirja(); 
    kirja1.rekisteroi(); 
    kirja1.taytaKirja(); 
    kirja2.rekisteroi(); 
    kirja2.taytaKirja(); 
    assertEquals("From: Kirjat line: 279", 0, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja2); 
    assertEquals("From: Kirjat line: 282", 2, kirjat.getLkm()); 
  } // Generated by ComTest END
}