package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.25 11:34:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi28 */
  @Test
  public void testRekisteroi28() {    // Kirja: 28
    Kirja kirja1 = new Kirja(); 
    assertEquals("From: Kirja line: 30", 0, kirja1.getTunnusNro()); 
    kirja1.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int n1 = kirja1.getTunnusNro(); 
    int n2 = kirja2.getTunnusNro(); 
    assertEquals("From: Kirja line: 36", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone50 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone50() throws CloneNotSupportedException {    // Kirja: 50
    Kirja kirja = new Kirja(); 
    kirja.parse("   1  |  Hobitti   | Tolkien"); 
    Kirja klooni = kirja.clone(); 
    assertEquals("From: Kirja line: 55", kirja.toString(), klooni.toString()); 
    kirja.parse("   4  |  Aapinen   | Kananen"); 
    assertEquals("From: Kirja line: 57", false, klooni.toString().equals(kirja.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta118 */
  @Test
  public void testAseta118() {    // Kirja: 118
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 120", null, kirja.aseta(1,"Hobitti")); 
    assertEquals("From: Kirja line: 121", "Vain numeroita!", kirja.aseta(3,"kissa")); 
    assertEquals("From: Kirja line: 122", null, kirja.aseta(3,"1937")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString175 */
  @Test
  public void testToString175() {    // Kirja: 175
    Kirja kirja = new Kirja(); 
    kirja.parse("   1  |  Hobitti  | Tolkien"); 
    assertEquals("From: Kirja line: 178", true, kirja.toString().startsWith("1|Hobitti|Tolkien|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse197 */
  @Test
  public void testParse197() {    // Kirja: 197
    Kirja kirja = new Kirja(); 
    kirja.parse("   1  |  Hobitti  | Tolkien"); 
    assertEquals("From: Kirja line: 200", 1, kirja.getTunnusNro()); 
    assertEquals("From: Kirja line: 201", true, kirja.toString().startsWith("1|Hobitti|Tolkien|")); 
    kirja.rekisteroi(); 
    int n = kirja.getTunnusNro(); 
    kirja.parse(""+(n)); 
    kirja.rekisteroi(); 
    assertEquals("From: Kirja line: 206", n+1, kirja.getTunnusNro()); 
  } // Generated by ComTest END
}