package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.25 11:39:58 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LainaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi35 */
  @Test
  public void testRekisteroi35() {    // Laina: 35
    Laina laina1 = new Laina(1,1); 
    assertEquals("From: Laina line: 37", 0, laina1.getTunnusNro()); 
    laina1.rekisteroi(); 
    Laina laina2 = new Laina(1,2); 
    laina2.rekisteroi(); 
    int n1 = laina1.getTunnusNro(); 
    int n2 = laina2.getTunnusNro(); 
    assertEquals("From: Laina line: 43", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString56 */
  @Test
  public void testToString56() {    // Laina: 56
    Laina laina = new Laina(1,1); 
    laina.parse("   1  |  1  | 1"); 
    assertEquals("From: Laina line: 59", true, laina.toString().startsWith("1|1|1")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse75 */
  @Test
  public void testParse75() {    // Laina: 75
    Laina laina = new Laina(1,1); 
    laina.parse("   1  |  1  | 1"); 
    assertEquals("From: Laina line: 78", 1, laina.getTunnusNro()); 
    assertEquals("From: Laina line: 79", true, laina.toString().startsWith("1|1|1")); 
    laina.rekisteroi(); 
    int n = laina.getTunnusNro(); 
    laina.parse(""+(n)); 
    laina.rekisteroi(); 
    assertEquals("From: Laina line: 84", n+1, laina.getTunnusNro()); 
  } // Generated by ComTest END
}