package kerho.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.27 23:59:16 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LainatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta70 
   * @throws PoikkeusException when error
   */
  @Test
  public void testLueTiedostosta70() throws PoikkeusException {    // Lainat: 70
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1), laina2 = new Laina(2,2); 
    lainat.lisaa(laina1); 
    lainat.lisaa(laina2); 
    Iterator<Laina> i = lainat.iterator(); 
    assertEquals("From: Lainat line: 79", laina1, i.next()); 
    assertEquals("From: Lainat line: 80", laina2, i.next()); 
    assertEquals("From: Lainat line: 81", false, i.hasNext()); 
    assertEquals("From: Lainat line: 82", 2, lainat.getLkm()); 
    lainat.poista(laina1.getTunnusNro()); 
    lainat.poista(laina2.getTunnusNro()); 
    assertEquals("From: Lainat line: 85", 0, lainat.getLkm()); 
    lainat.tallenna(); 
    lainat.lueTiedostosta(); 
    int lkm1 = lainat.getLkm(); 
    lainat.tallenna(); 
    lainat = new Lainat(); 
    assertEquals("From: Lainat line: 91", 0, lainat.getLkm()); 
    lainat.lisaa(laina1); 
    lainat.lisaa(laina2); 
    assertEquals("From: Lainat line: 94", lkm1 + 2, lainat.getLkm()); 
    lainat.poista(laina1.getTunnusNro()); 
    lainat.poista(laina2.getTunnusNro()); 
    assertEquals("From: Lainat line: 97", lkm1, lainat.getLkm()); 
    lainat.tallenna(); 
    lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    assertEquals("From: Lainat line: 101", lkm1, lainat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa190 
   * @throws PoikkeusException when error
   */
  @Test
  public void testLisaa190() throws PoikkeusException {    // Lainat: 190
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1); 
    Laina laina2 = new Laina(2,2); 
    assertEquals("From: Lainat line: 195", 0, lainat.getLkm()); 
    lainat.lisaa(laina1); assertEquals("From: Lainat line: 196", 1, lainat.getLkm()); 
    lainat.lisaa(laina2); assertEquals("From: Lainat line: 197", 2, lainat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista211 
   * @throws PoikkeusException when error
   */
  @Test
  public void testPoista211() throws PoikkeusException {    // Lainat: 211
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1); 
    Laina laina2 = new Laina(2,2); 
    assertEquals("From: Lainat line: 216", 0, lainat.getLkm()); 
    lainat.lisaa(laina1); assertEquals("From: Lainat line: 217", 1, lainat.getLkm()); 
    lainat.lisaa(laina2); assertEquals("From: Lainat line: 218", 2, lainat.getLkm()); 
    lainat.poista(laina1.getTunnusNro()); assertEquals("From: Lainat line: 219", 1, lainat.getLkm()); 
    lainat.poista(laina2.getTunnusNro()); assertEquals("From: Lainat line: 220", 0, lainat.getLkm()); 
  } // Generated by ComTest END
}